### ISSUE TITLE
whatshap works for haploid organisms?

### ISSUE THREAD

**Issue by dcastaneda5** [whatshap/whatshap-gh-backup#2]
Hi! I am currently working on a malaria project, and I am trying to phase haplotypes based on 2 gene markers from malaria. However, in human blood we find the parasite in its haploid form, not diploid. I was wondering if whatshap can handle haploid organisms.

thanks!

**Comment by marcelm** [comment]
Closing here, this was transferred to https://github.com/whatshap/whatshap/issues/235
