### ISSUE TITLE
Haplotag consistently finds more reads for HP1 than HP2

### ISSUE THREAD

**Issue by SAMtoBAM** [whatshap/whatshap-gh-backup#3]
Hello, 

I have several samples I have phased and then used haplotag on the reads.
However one feature I find consistent across all the genomes is the haplotype1 has more reads than haplotype2. The genomes are diploid and euploid and therefore I would imagine that each haplotype variant is represented by an equal number of reads

Have you any idea why this might be?
Thanks for the help

**Comment by marcelm** [comment]
Closing here, this was moved over to https://github.com/whatshap/whatshap/issues/234
